import { CAMPUS_CENTER } from "../config";

// ---------------------------------------------------------------------
// DEMO / SAMPLE DATA ONLY.
// These records do not represent real surveyed sites. They exist so the
// dashboard has something to render on first load. Replace with real
// data from siteService once a backend is wired up.
// ---------------------------------------------------------------------

const offset = (dLat, dLng) => ({
  latitude: CAMPUS_CENTER.lat + dLat,
  longitude: CAMPUS_CENTER.lng + dLng,
});

const PLACEHOLDER_PHOTOS = [
  "https://picsum.photos/seed/site-a/640/420",
  "https://picsum.photos/seed/site-b/640/420",
  "https://picsum.photos/seed/site-c/640/420",
];

function photoSet(seed, count) {
  return Array.from({ length: count }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/640/420`);
}

export const SAMPLE_SITES = [
  {
    id: "SITE-024",
    issueType: "sand",
    description: "Sand pile beside the civil engineering block extension, growing over the past two weeks.",
    ...offset(0.0021, -0.0028),
    reportedAt: "2026-09-06T09:12:00+05:30",
    status: "pending",
    severity: "high",
    estimatedVolume: 18.6,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 2.0,
    photos: photoSet("s024", 4),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-023",
    issueType: "debris",
    description: "Broken brick and rubble left after the hostel-block facade repair.",
    ...offset(-0.0016, 0.0034),
    reportedAt: "2026-09-04T14:40:00+05:30",
    status: "in_review",
    severity: "medium",
    estimatedVolume: 9.2,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.5,
    photos: photoSet("s023", 3),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-022",
    issueType: "waste",
    description: "Waste accumulation behind the mess kitchen, bins overflowing.",
    ...offset(0.0009, 0.0041),
    reportedAt: "2026-09-03T08:05:00+05:30",
    status: "in_progress",
    severity: "medium",
    estimatedVolume: 3.4,
    volumeUnit: "m³",
    scalingMethod: "lidar",
    referenceDistance: null,
    photos: photoSet("s022", 3),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-021",
    issueType: "obstruction",
    description: "Scaffolding material narrowing the footpath near the central library entrance.",
    ...offset(-0.0031, -0.0009),
    reportedAt: "2026-09-02T11:20:00+05:30",
    status: "pending",
    severity: "high",
    estimatedVolume: 2.1,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s021", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-020",
    issueType: "sand",
    description: "Sand delivery stockpile for the new lab building, partially tarped.",
    ...offset(0.0038, 0.0006),
    reportedAt: "2026-08-30T16:00:00+05:30",
    status: "in_progress",
    severity: "medium",
    estimatedVolume: 27.9,
    volumeUnit: "m³",
    scalingMethod: "lidar",
    referenceDistance: null,
    photos: photoSet("s020", 4),
    video: null,
    modelUrl: "https://example.com/models/site-020.glb",
  },
  {
    id: "SITE-019",
    issueType: "debris",
    description: "Demolition debris from the old workshop roof, partly cleared.",
    ...offset(-0.0008, -0.0037),
    reportedAt: "2026-08-28T10:30:00+05:30",
    status: "resolved",
    severity: "low",
    estimatedVolume: 6.0,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 2.0,
    photos: photoSet("s019", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-018",
    issueType: "waste",
    description: "Construction-crew lunch waste and packaging near the site office.",
    ...offset(0.0027, 0.0022),
    reportedAt: "2026-08-27T13:10:00+05:30",
    status: "resolved",
    severity: "low",
    estimatedVolume: 1.2,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s018", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-017",
    issueType: "obstruction",
    description: "Pipe stack partially blocking the service road behind the boys' hostel.",
    ...offset(-0.0022, 0.0012),
    reportedAt: "2026-08-25T09:45:00+05:30",
    status: "pending",
    severity: "medium",
    estimatedVolume: 4.5,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.5,
    photos: photoSet("s017", 3),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-016",
    issueType: "sand",
    description: "Small sand heap near the sports complex, likely for the running-track edging work.",
    ...offset(0.0014, -0.0044),
    reportedAt: "2026-08-22T15:25:00+05:30",
    status: "in_review",
    severity: "low",
    estimatedVolume: 5.7,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s016", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-015",
    issueType: "debris",
    description: "Concrete offcuts and formwork scraps outside the new academic block.",
    ...offset(-0.0037, -0.0021),
    reportedAt: "2026-08-20T12:00:00+05:30",
    status: "in_progress",
    severity: "high",
    estimatedVolume: 22.3,
    volumeUnit: "m³",
    scalingMethod: "lidar",
    referenceDistance: null,
    photos: photoSet("s015", 4),
    video: null,
    modelUrl: "https://example.com/models/site-015.glb",
  },
  {
    id: "SITE-014",
    issueType: "waste",
    description: "General waste dumping near the back gate, recurring issue.",
    ...offset(0.0042, -0.0017),
    reportedAt: "2026-08-18T07:50:00+05:30",
    status: "pending",
    severity: "high",
    estimatedVolume: 7.8,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 2.0,
    photos: photoSet("s014", 3),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-013",
    issueType: "other",
    description: "Unused steel reinforcement bars stacked along the footpath, tripping hazard.",
    ...offset(-0.0013, 0.0038),
    reportedAt: "2026-08-16T17:15:00+05:30",
    status: "in_review",
    severity: "medium",
    estimatedVolume: 1.9,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s013", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-012",
    issueType: "sand",
    description: "Sand and gravel mix near the guest house driveway extension.",
    ...offset(0.0006, 0.0009),
    reportedAt: "2026-08-14T10:10:00+05:30",
    status: "resolved",
    severity: "low",
    estimatedVolume: 4.1,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s012", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-011",
    issueType: "obstruction",
    description: "Temporary fencing and material stacked across the cycle path near Gate 3.",
    ...offset(-0.0041, 0.0005),
    reportedAt: "2026-08-12T08:30:00+05:30",
    status: "in_progress",
    severity: "medium",
    estimatedVolume: 3.0,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.5,
    photos: photoSet("s011", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-010",
    issueType: "debris",
    description: "Tile and plaster debris outside the renovated department office.",
    ...offset(0.0031, 0.0033),
    reportedAt: "2026-08-10T14:00:00+05:30",
    status: "resolved",
    severity: "low",
    estimatedVolume: 2.6,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s010", 2),
    video: null,
    modelUrl: null,
  },
  {
    id: "SITE-009",
    issueType: "waste",
    description: "Packaging waste from furniture delivery at the new hostel block.",
    ...offset(-0.0006, -0.0011),
    reportedAt: "2026-08-08T09:20:00+05:30",
    status: "pending",
    severity: "medium",
    estimatedVolume: 2.0,
    volumeUnit: "m³",
    scalingMethod: "two_point",
    referenceDistance: 1.0,
    photos: photoSet("s009", 2),
    video: null,
    modelUrl: null,
  },
];
